### PR TITLE
Add neo4j support

### PR DESCRIPTION
**Pull request by atomfrede**
I hope the setup is correct. Just testing default config for neo4j with gradle and maven within the nosql tests

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
It doesn't work... Can you have a look plz @atomfrede ?
https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build?definitionId=11&_a=summary

**Comment by atomfrede** [comment]
It looks like a node installation problem. :thinking: Will have a look

**Comment by pascalgrimaud** [comment]
Sorry, here the exact logs: https://dev.azure.com/hipster-labs/jhipster-daily-builds/_build/results?buildId=10741&view=logs&j=ceed2553-232e-5603-78a1-6ddbcc966c2e&t=d4b5f485-af58-5ed4-89d3-27113c3fcd3a

Here an extract of the stacktrace:

```
[INFO] /home/vsts/app/src/main/java/io/github/jhipster/travis/security/jwt/TokenProvider.java: Recompile with -Xlint:deprecation for details.
[INFO] /home/vsts/app/src/main/java/io/github/jhipster/travis/config/neo4j/Neo4jMigrations.java: /home/vsts/app/src/main/java/io/github/jhipster/travis/config/neo4j/Neo4jMigrations.java uses unchecked or unsafe operations.
[INFO] /home/vsts/app/src/main/java/io/github/jhipster/travis/config/neo4j/Neo4jMigrations.java: Recompile with -Xlint:unchecked for details.
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/vsts/app/src/main/java/io/github/jhipster/travis/web/rest/OperationResource.java:[100,39] cannot find symbol
  symbol:   method findAllWithEagerRelationships(org.springframework.data.domain.Pageable)
  location: variable operationRepository of type io.github.jhipster.travis.repository.OperationRepository
[ERROR] /home/vsts/app/src/main/java/io/github/jhipster/travis/web/rest/OperationResource.java:[117,60] cannot find symbol
  symbol:   method findOneWithEagerRelationships(java.lang.String)
  location: variable operationRepository of type io.github.jhipster.travis.repository.OperationRepository
```

**Comment by atomfrede** [comment]
Thanks. Still a bit confusing by all the builds and the azure ui.

**Comment by atomfrede** [comment]
Just a reminder for me, seems we forgot something here   https://github.com/jhipster/generator-jhipster/blob/5d64b6cdddb76d14820bc495b98e06986bead77b/generators/entity-server/templates/src/main/java/package/repository/EntityRepository.java.ejs#L105 will try to have look this evening.

**Comment by atomfrede** [comment]
@pascalgrimaud FYI working on it, we most likely discovered another but in SDN/RX which we will try to fix

**Comment by pascalgrimaud** [comment]
ok thanks
nothing urgent, these daily builds are just here to detect failures :)
take your time to fix it

**Pull request merged**
