### PR TITLE
Update Ubuntu Image in all Pipelines

### PR DESCRIPTION
**Pull request by SudharakaP**
This updates the Ubuntu VM image to latest in all daily build pipelines. 

Fixes https://github.com/jhipster/generator-jhipster/issues/10662

### CODE REVIEW

**Comment by vishal423** [comment]
how about using `ubuntu-latest` tag to ensure we always remain on latest LTS?

**Comment by SudharakaP** [comment]
@vishal423 : I was contemplating about this for a while but then thought what if they update their `ubuntu-latest` to `20.06` or whatever the next LTS version is; or I am not sure whether they guarantee `ubuntu-latest` is always a LTS version. It might give us unintended side effects? :smile: 

In either case I am okay with this change; it's just me choosing fixed version over the unfixed `ubuntu-latest` tag. 

@pascalgrimaud : What do you think? If you also like `ubuntu-latest` instead, I'll go ahead and change it. :smile:

**Comment by vishal423** [comment]
@SudharakaP, I believe support should always be LTS across CI providers. There is a risk of the introduction of breaking changes with LTS upgrades (like seen on `Travis`), but, I don't see that as a big issue.

**Comment by pascalgrimaud** [comment]
Yes, we should keep and use LTS, to be consistent between our official Docker image, DevBox, CI etc

**Comment by pascalgrimaud** [comment]
let's give a try !
thanks @SudharakaP !

**Comment by SudharakaP** [comment]
@pascalgrimaud : I think what [@vishal423 is suggesting](https://github.com/hipster-labs/jhipster-daily-builds/pull/27#issuecomment-544784772) is to always use `ubuntu-latest` instead of fixing it to `ubuntu-`18.04` which is what I have done. What approach do you prefer? :smile:

**Comment by pascalgrimaud** [comment]
I'd prefer consistency:
- Docker image: https://github.com/jhipster/generator-jhipster/blob/master/Dockerfile#L1
- DevBox: https://github.com/jhipster/jhipster-devbox/blob/master/Vagrantfile#L2

For NodeJS, we suggest to our user to always use Node LTS.

So I think it's better for our user to stay on Ubuntu 18.04 LTS.

**Pull request merged**
