### PR TITLE
Update 10-install-jhipster-daily-builds.sh

### PR DESCRIPTION
**Pull request by mshima**

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
you're awesome, thanks @mshima !! :)

**Comment by mshima** [comment]
😄 failures Doesn’t seems related to bom nor to cli.
Don’t know what happened now.

**Comment by pascalgrimaud** [comment]
Yeah... I'll investigate this weekend, don't have time right now

**Comment by pascalgrimaud** [comment]
I added some logs in the CI and now we have the reason why it failed
it contains some properties related to metrics, which have not been deleted

I'll take care of this

**Comment by mshima** [comment]
@pascalgrimaud we should add workflow_dispatch event to daily builds workflows.
It allows to manually trigger a build.

**Comment by pascalgrimaud** [comment]
I don't know that option, but if it helps to trigger manually the builds, yes  +1

**Pull request merged**
