### PR TITLE
update ci using npm commands instead of script

### PR DESCRIPTION
**Pull request by Tcharl**
related to https://github.com/jhipster/generator-jhipster/pull/18776#issuecomment-1142167225

### CODE REVIEW

**Comment by Tcharl** [comment]
@DanielFran I tried to fix the script update using standard npm commands like we have in the generator.
I absolutely don't know how this repo works: can you please guide me (maybe enriching the contributing.md)?

**Review by DanielFran — APPROVED** [review]

**Comment by DanielFran** [comment]
@pascalgrimaud can you review please (cannot merge)

**Comment by mshima** [comment]
Non jdl samples looks ok.
The jdl samples will fail, they are microservices samples.
But I think it’s time to migrate them to workspaces.

**Comment by Tcharl** [comment]
@mshima you take it? I don't know how workspace + ci works.
I'm really interested by the review, so that I'll be able to reproduce

**Pull request merged**
